configfile: 'config.yaml'

# Version without wrappers
# include: 'alignment.smk'
# include: 'variants.smk'

# Version with wrappers
include: 'alignment_wrappers.smk'
include: 'variants_wrappers.smk'

rule all:
    input:
        'results/variants.tsv'
