configfile: 'config.yaml'

# Version without wrappers
# include: 'rules/alignment.smk'
# include: 'rules/variants.smk'

# Version with wrappers
include: 'rules/alignment_wrappers.smk'
include: 'rules/variants_wrappers.smk'

rule all:
    input:
        'results/variants.tsv'
